import React from "react";
import { notFound } from "next/navigation";
import { loadPlanGraph } from "@raah/db";
import { db } from "@/lib/db";
import { ItineraryDocument } from "@/components/itinerary/ItineraryDocument";

// Simplified layout for print, removing interactivity
export default async function PrintTripPage({ params }: { params: { id: string } }) {
  const loaded = await loadPlanGraph(db, params.id).catch(() => null);

  if (!loaded) return notFound();
  const graph = loaded.graph;

  return (
    <div className="bg-white text-black font-serif print-container max-w-[800px] mx-auto p-8">
      {/* 
        Use CSS print media query for styling:
        @media print {
          .print-container { padding: 0; }
          .no-print { display: none; }
          .page-break { page-break-after: always; }
        }
      */}
      <style
        dangerouslySetInnerHTML={{
          __html: `
        @media print {
          body { background: white; }
          .no-print { display: none !important; }
          .page-break { page-break-after: always; }
          * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
        }
      `,
        }}
      />

      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold mb-2">{graph.concept.title}</h1>
        <p className="text-lg text-gray-600">Your personalized itinerary from Raah</p>
      </div>

      <div className="mb-8">
        <p>{graph.concept.narrative}</p>
      </div>

      <ItineraryDocument graph={graph as any} />

      <div className="text-center text-sm text-gray-500 mt-12 pt-8 border-t">
        Generated by Raah AI Travel Planner
      </div>
    </div>
  );
}
